export default function PerformancePage() {
  return (
    <main className="min-h-screen bg-black text-white px-6 py-12">
      <section className="max-w-5xl mx-auto">
        <h1 className="text-4xl font-bold mb-6">
          Paper-Trading Performance
        </h1>

        <p className="text-gray-300 text-lg mb-8">
          V4 Signals tracks simulated paper trades generated by the signal bot.
          These results help users study the signal system and understand how it
          performs in simulated conditions.
        </p>

        <div className="grid md:grid-cols-4 gap-6 mb-10">
          <div className="bg-gray-900 p-6 rounded-xl">
            <p className="text-gray-400 text-sm">Closed Paper Trades</p>
            <p className="text-3xl font-bold mt-2">Coming Soon</p>
          </div>

          <div className="bg-gray-900 p-6 rounded-xl">
            <p className="text-gray-400 text-sm">Win Rate</p>
            <p className="text-3xl font-bold mt-2">Coming Soon</p>
          </div>

          <div className="bg-gray-900 p-6 rounded-xl">
            <p className="text-gray-400 text-sm">Average Result</p>
            <p className="text-3xl font-bold mt-2">Coming Soon</p>
          </div>

          <div className="bg-gray-900 p-6 rounded-xl">
            <p className="text-gray-400 text-sm">Open Paper Trades</p>
            <p className="text-3xl font-bold mt-2">Coming Soon</p>
          </div>
        </div>

        <section className="bg-gray-900 p-6 rounded-xl mb-8">
          <h2 className="text-2xl font-bold mb-3">
            What Counts as Paper-Trading Performance?
          </h2>
          <p className="text-gray-400">
            Paper-trading performance means the app is tracking simulated trades.
            These trades are not placed on a real exchange and do not use real
            customer funds.
          </p>
        </section>

        <section className="bg-gray-900 p-6 rounded-xl mb-8">
          <h2 className="text-2xl font-bold mb-3">
            Why Paper Trading Matters
          </h2>
          <p className="text-gray-400">
            Paper trading lets users review signals, confidence scores, trade
            reasoning, and simulated outcomes before making their own independent decisions.
          </p>
        </section>

        <section className="bg-red-900/30 border border-red-700 p-6 rounded-xl">
          <h2 className="text-2xl font-bold mb-3">
            No Profit Guarantees
          </h2>
          <p className="text-gray-300">
            Paper-trading results are not the same as real trading results.
            Crypto markets are risky and unpredictable. V4 Signals does not
            guarantee profits, does not provide financial advice, and does not
            execute trades for users.
          </p>
        </section>
      </section>
    </main>
  );
}
